version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
